# Generated by Django 2.2.14 on 2020-12-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=100)),
                ('duracion', models.IntegerField(null=True)),
                ('horarios', models.CharField(max_length=30)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
    ]
