# Generated by Django 2.2.14 on 2020-12-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('grado', models.CharField(max_length=20)),
                ('grupo', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=200)),
                ('calificacion', models.IntegerField(null=True)),
                ('asistencia', models.IntegerField(null=True)),
                ('clases', models.ManyToManyField(related_name='clases', to='Materias.Asignatura')),
            ],
        ),
    ]
