# Generated by Django 2.2.14 on 2020-12-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('profesion', models.CharField(max_length=100)),
                ('clases_impartidas', models.ManyToManyField(related_name='clases_impartidas', to='Materias.Asignatura')),
            ],
        ),
    ]
